# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path


  
# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build Windows x64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: maven
    - run: mkdir daemon staging

    - run: mkdir staging && cp target/*.* staging
    - name: download daemon
      uses: duhow/download-github-release-assets@v1
      with:
        repository: unigrid-project/daemon
        tag: 2.0.1
        files: unigrid-2.0.1-win64.zip
        target: unigridd.zip
    - name: Extract
      run: | 
        mkdir staging/daemon && unzip unigridd.zip -d staging/daemon
    - run: cp stating/daemon/unigrid daemon

    - name: Build with Maven
      run: mvn install
      
    - run: mkdir staging && cp target/release/*.* staging
    - uses: actions/upload-artifact@v3
      with:
       name: Package
       path: staging
       
