# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: ubuntu/deb build x64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: maven
        
    - run: mkdir -p src/main/resources/daemon
    
    - name: download daemon
      uses: duhow/download-github-release-assets@v1
      with:
        repository: unigrid-project/daemon
        release-id: latest
        files: unigrid-*-x86_64-linux-gnu.tar.gz
        target: unigridd.tar.gz
    - name: Extract
      run: | 
        tar -xvf unigridd.tar.gz && cp unigrid-2.0.1/bin/unigridd src/main/resources/daemon
        
    - name: Build with Maven
      run: mvn install
      
    - run: mkdir staging && cp target/release/*.* staging
    - uses: actions/upload-artifact@v3
      with:
       name: Package
       path: staging
